import type { Metadata } from "next";
import { poppins } from "./fonts";
import { Providers } from './providers'


export const metadata: Metadata = {
  title: "Meu App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
      <Providers>{children}</Providers>
      </body>
    </html>
  );
}
